version: "3.8"

services:
  db:
    container_name: mysql_db
    image: mysql:8.0.36-bullseye
    restart: always
    ports:
      - "3306:3306"
    volumes:
      #- mysql-db:/var/lib/mysql
      - ./mysql_db:/var/lib/mysq
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=matricula_DS-20226
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=123456

  phpmyadmin:
    depends_on:
      - db
    container_name: php_ma
    image: phpmyadmin:5.2.0-apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./php_ma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./php_ma/custom/phpmyadmin/themeName/:/var/www/html/themes/themeName/
    environment:
      - PMA_ARBITRARY=1
#volumes:
#  mysql-db:
#    external: true
